In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

```Simple Linear Regression Using Gradient Descent```
#the relationship between student test scores and hours of study
#Intuitively, there must be a relationship right? The more you study, the better your test scores 

In [46]:
data = np.genfromtxt("../linear_regression_live-master/data.csv", delimiter=",")

In [47]:
data[0:10]

array([[32.50234527, 31.70700585],
       [53.42680403, 68.77759598],
       [61.53035803, 62.5623823 ],
       [47.47563963, 71.54663223],
       [59.81320787, 87.23092513],
       [55.14218841, 78.21151827],
       [52.21179669, 79.64197305],
       [39.29956669, 59.17148932],
       [48.10504169, 75.3312423 ],
       [52.55001444, 71.30087989]])

In [48]:
X = data[:,0] 
y = data[:,1]  


In [49]:
X

array([32.50234527, 53.42680403, 61.53035803, 47.47563963, 59.81320787,
       55.14218841, 52.21179669, 39.29956669, 48.10504169, 52.55001444,
       45.41973014, 54.35163488, 44.1640495 , 58.16847072, 56.72720806,
       48.95588857, 44.68719623, 60.29732685, 45.61864377, 38.81681754,
       66.18981661, 65.41605175, 47.48120861, 41.57564262, 51.84518691,
       59.37082201, 57.31000344, 63.61556125, 46.73761941, 50.55676015,
       52.22399609, 35.56783005, 42.43647694, 58.16454011, 57.50444762,
       45.44053073, 61.89622268, 33.09383174, 36.43600951, 37.67565486,
       44.55560838, 43.31828263, 50.07314563, 43.87061265, 62.99748075,
       32.66904376, 40.16689901, 53.57507753, 33.86421497, 64.70713867,
       38.11982403, 44.50253806, 40.59953838, 41.72067636, 51.08863468,
       55.0780959 , 41.37772653, 62.49469743, 49.20388754, 41.10268519,
       41.18201611, 50.18638949, 52.37844622, 50.13548549, 33.64470601,
       39.55790122, 56.13038882, 57.36205213, 60.26921439, 35.67

In [50]:
y

array([ 31.70700585,  68.77759598,  62.5623823 ,  71.54663223,
        87.23092513,  78.21151827,  79.64197305,  59.17148932,
        75.3312423 ,  71.30087989,  55.16567715,  82.47884676,
        62.00892325,  75.39287043,  81.43619216,  60.72360244,
        82.89250373,  97.37989686,  48.84715332,  56.87721319,
        83.87856466, 118.5912173 ,  57.25181946,  51.39174408,
        75.38065167,  74.76556403,  95.45505292,  95.22936602,
        79.05240617,  83.43207142,  63.35879032,  41.4128853 ,
        76.61734128,  96.76956643,  74.08413012,  66.58814441,
        77.76848242,  50.71958891,  62.12457082,  60.81024665,
        52.68298337,  58.56982472,  82.90598149,  61.4247098 ,
       115.2441528 ,  45.57058882,  54.0840548 ,  87.99445276,
        52.72549438,  93.57611869,  80.16627545,  65.10171157,
        65.56230126,  65.28088692,  73.43464155,  71.13972786,
        79.10282968,  86.52053844,  84.74269781,  59.35885025,
        61.68403752,  69.84760416,  86.09829121,  59.10

In [43]:
data.shape


(100, 2)

In [38]:
#splitting dataset into training set and test set
from sklearn.model_selection   import train_test_split

In [39]:
train_test_split??

In [40]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [52]:
X_test


array([57.31000344, 51.0887199 , 61.53035803, 55.0780959 , 44.49285588,
       46.2309665 , 44.68719623, 43.10782022, 51.08863468, 50.03017434,
       41.72067636, 68.76573427, 55.80573336, 58.16847072, 39.29956669,
       52.22399609, 47.48120861, 51.84518691, 58.16454011, 48.10504169])

In [30]:
X

[1, 2]